### ISSUE TITLE
fworld can never find the pats file

### ISSUE THREAD

**Issue by etuleu** [Astera-org/obelisk#211]
This is running using infra. For some reason we can never find this file.

STDOUT:  08-09 16:41:16, Error: ERROR! Can't find pats file! This will prevent the model from working! :open package/pats.json: no such file or directory

**Comment by jedmccaleb** [comment]
in your local infra to the actual cluster?

**Comment by garymm** [comment]
I changed it to look for the file in a path that's relative to the repo root, rather than the directory where the source code is:
https://github.com/Astera-org/obelisk/pull/351/files#diff-8b20563ce4ddf433740b910a8e9506229c2f48e39fcc3b532a50938631d87eea

Hopefully fixed.
Closing since I don't think we care about running FWorld on Infra anyways, but feel free to re-open.
